- SeniorProject25/models/database.js
- SeniorProject25/signup.html
- SeniorProject25/viewmodels/login.js
- SeniorProject25/viewmodels/signup.js
this was the feature that inplements the reset password. added a listen in login.js 
adds in a popup for when user wants to reset the passwrd and enter in the email 
the user receives email nad resets. and user will come back manually to login with the new password.
> Himalforgot password

- SeniorProject25/models/database.js
- SeniorProject25/onboarding.html
- SeniorProject25/signup.html
- SeniorProject25/styles/onboarding.css
- SeniorProject25/viewmodels/login.js
- SeniorProject25/viewmodels/onboarding.js
- SeniorProject25/viewmodels/signup.js
New onboarding page
New forgot password functionality
> Himal onboarding screen

- dashboard.js
- home.html
updated the home and budget cha
> updated home.html and dashboard.js with pie chart

- community.js
implemented the ui for the search bar in the community page.
> created a searhc bar on the top of the community.html / community.js

- budget.html
Alex: i have updated the UI for the budget. (4/16/2025)
i will update some things for the Fasting Ui as well when i get home tonight (4/16/2025)
> updated the html for budget UI

- budget.html
- style.css
> Alex budget fasting UI changes

- firebase-config.js
just updated the firebase .js  
const firebaseConfig = {
apiKey: "AIzaSyD1iXSx2Y22IzeVcmUoVacPR5fVMp1SJpg",
authDomain: "testingvidia.firebaseapp.com",
projectId: "testingvidia",
storageBucket: "testingvidia.firebasestorage.app",
messagingSenderId: "98113240298",
appId: "1:98113240298:web:f1871fda29b7d5f7996b93"
};
> changes the firebase-config.js

- ai-advice.js
- dashboard.js
- exercise.js
- firebase-config.js
- goal.js
> Himal upgrades

- budget.html
- fasting.html
- fasting.js
- firebase-config.js
- index.html
- style.css
> Alex upgrades

- community.html
- community.js
- style.css
alex added a filter to the community page
> Added filter for community page to see posts based on post tags

- messaging.html
> updated text

- goalsweight.js
- goalsweightpage.html
the changes features i have did this push is 
1. Change goal type from “Lose Weight” to “Lose or Gain Weght”
2. Update “Log Your Weight” so the weight change is reflected in the user’s profile as well
3. Change section title from “Your Goal” to “Your Weight Goal”
remaining to do is : 
1. Update Progress in “Your Goal” section to calculate progress based on most recent weight and previous weight
2. “Target Value” should not be equal to current weight, user should be notified to “enter a valid target weight”
> Himal weight upgrades

- recipe.html
"the changes features i have did this push is:
1. Change goal type from “Lose Weight” to “Lose or Gain Weght”. 
2. Update “Log Your Weight” so the weight change is reflected in the user’s profile as well.
3. Change section title from “Your Goal” to “Your Weight Goal” 
**### Remaining changes to push are:**
1.Update Progress in “Your Goal” section to calculate progress based on most recent weight and previous weight “Target Value” 
2.should not be equal to current weight, user should be notified to “enter a valid target weight”
> 5-6-2025 Himal @10:24Pm:

- goalsweight.js
- goalsweightpage.html
makes it so that the progress bar shows progress
> Progressbarhimal

- budget.html
- community.html
- community.js
- fasting.html
- fasting.js
- home.html
- nutrition.html
- nutrition.js
- profile.js
- recipe.html
- recipe.js
- style.css
Removed "From Date to Date" in the Budget Overview. Added a date and time field (only for previous days) where you can log a meal for a day and time in the past if forgotten. You can still log meals for the current day and it will fetch the current time you logged it of that day still. Added a search bar to lookup users as well as a Friend List icon and Notification icon where you can see your friends added and friend requests respectively. Also updated avatars so that it shows the initials of the name on the profile. Lastly, to distinguish multiple profiles with the same name, there is a unique hash value attached to different profiles with the same name so the user doesn't get confused who is who. Lastly, the fasting logic and fasting in general was simplified where you can only start …
> Budget, Nutrition, Community and Fasting Upgrades

- profile.html
- profile.js
> removed the redundant age input and logic

- goalsweightpage.html
made it so that you are not able to create a goal for the past
> made it so that you can not create goals for the past

- README.md
- budget.html
- budget.js
- community.html
- community.js
- dashboard.js
- exercise.html
- exercise.js
- fasting.html
- fasting.js
- goalsweight.js
- home.html
- nutrition.html
- nutrition.js
- profile.js
- recipe.html
- recipe.js
- style.css
- workout.js
Implemented a drop down for sharing recipes on the community page and made it so that multiple recipes can be shared in one post from your saved recipes in the recipes page. Removed the Fasting History list on the Fasting Page to reduce redundancy. Fixed the logging issues on exercise page where workouts weren't be logged for previous days. Restricted logging a date for the budget only within the selected budget period. Fixed BMI calculation on the dashboard and made charts look cleaner. Also fixed general bugs with some of the pages.
> Alex final upgrades

- fasting.js
Fixed a bug where if the user has already logged a fast for the day, but they reload the page, the system will let them start and stop another one each time they reload.
> Fasting Bug Fix

- home.html
i replaced the daily tips wiht the random tips and it updates every 10 sedonds
> Random daily tip fix himal dashboard

- budget.js
Fixed a bug in which the minimum date you could set the date and time calendar to, was a day after your budget period started and not the actual day it started.
> Budget Bug Fix

- ai-advice.html
- ai-advice.js
- ai-meals.html
- community.js
- dashboard.js
- exercise.html
- goalsweight.js
- home.html
- nutrition.js
- recipe.js
- sidebar.js
✅ Tasks I Completed
Removed the age input field from onboarding/profile – only DOB is used so AI can calculate age automatically.(himal)
Re-added the "Forgot Password" feature.(himal)
Fixed the progress bar – it now updates correctly when logging weight.(himal)
Added logic to disable editing a goal after it’s been achieved.(himal)
Ensured AI recognizes and uses date of birth instead of age.(himal)
Fixed the daily tips feature – now shows random tips every 10 seconds.(himal)
Worked with Wali to set up OpenAI API key input – user enters it once to activate AI features. (waleed created)
Fixed the broken friend request system. (himal)
Merged all changes (including Wali’s) into the main branch.(himal)
> Removed non functional ai himal

- ai-advice.html
- ai-advice.js
- ai-meals.html
- community.js
- dashboard.js
- exercise.html
- goalsweight.js
- home.html
- nutrition.js
- recipe.js
- sidebar.js
so that it will ask you to fill out the profile if it is not
> back to the basic rollback
